[app]
  #app名称
  name = "project-web"
  url = "http://localhost"
  port = ":8080"
  debug = false

[database]
  dirver = "mysql"

[mysql]
  dbname = "@tcp(127.0.0.1:3306)/superstar?charset=utf8"
  username = "root"
  password = "333"

[website]
  static_uri = "/static"
  site_title = "后台管理"
  copy_right = "<small>&copy;2019</small>"

[image]
  basePath = "../uploads"
  imgPath = "../uploads"