[app]
  #app名称
  name = "project-web"
  url = "http://localhost"
  port = ":8080"
  debug = false

[database]
  dirver = "mysql"

[mysql]
  dbname = "@tcp(127.0.0.1:3306)/dbname?charset=utf8"
  username = "root"
  password = "password"

[website]
  static_uri = "/static"
  site_title = "后台管理"
  copy_right = "<small>&copy;2019</small>"
